baseURL = "https://psiaklika.pl"
languageCode = "pl-PL"
title = "Psia Klika"
theme = "timer-hugo"
publishdir = "../"
enableRobotsTXT = true

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "O Nas"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Oferta Szkoleń"
        url     = "/offer"
        weight  = 3
    # [[menu.nav]]
    #     name    = "Hotel"
    #     url     = "/hotel"
    #     weight  = 4
    [[menu.nav]]
        name    = "Terminy i Cennik"
        url     = "/pricing"
        weight  = 5
    [[menu.nav]]
        name    = "Kontakt"
        url     = "/contact"
        weight  = 6

# Site Params
[params]
    home = "Strona Główna"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Psia Klika -- szkolenia dla Twojego psa i nie tylko"
    author = "Piotr Wojciechowski"
    keywords = "psiaklika,psia,klika,psy,szkolenia,psi hotel,psie szkolenia,hotel dla psów"
    # Google Analitycs
    googleAnalitycsID = "UA-90751160-2"
    facebook = "https://www.facebook.com/psiaklika"
    instagram = "https://instagram.com/psiaklika"
    twitter = "https://twitter.com"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "PSIA KLIKA"
        description = "SZKOLENIA DLA TWOJEGO PSA I NIE TYLKO!"
        btn     = false
        btnText = "Download More"
        btnURL  = "https://themefisher.com/"
        [[params.banner.flipText]]
            title   = "SZKOLENIA"
        [[params.banner.flipText]]
            title   = "HOTEL"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "Dlaczego my?"
        content = "Szkoła Psia Klika prowadzi szkolenia dla psów w każdym wieku i każdej rasy. Naszą misją jest budowanie mocnej i prawidłowej relacji między psem i jego właścicielem. Pracujemy używając jedynie pozytywnych metod szkoleniowych."
        image   = "images/about/logo-big.png"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "ZAPRASZAMY DO KONTAKTU"
        content = "Napisz lub zadzowń do nas! Chętnie udzielimy więcej informacji i pomożemy w wyborze odpowiedniej oferty dla Ciebie i Twojego psa."
        btnText = "Napisz do nas"
        btnURL  = "/contact"
    